# TAGS: Used to execute or skip specific tasks in a playbook

- name: First Playbook
  hosts: all
  tasks:
    - name: Install Git
      yum:
        name: git
        state: present
      tags: install_git

    - name: Install Maven
      yum:
        name: maven
        state: present
      tags: install_maven

    - name: Create User
      user:
        name: test
        state: present
      tags: create_user

#Usage Instructions:
#Run a Single Tag: ansible-playbook ansible-tags.yaml --tags install_git
#Run Multiple Tags: ansible-playbook ansible-tags.yaml --tags install_maven,create_user
#Skip a Single Tag: ansible-playbook ansible-tags.yaml --skip-tags create_user
#Skip Multiple Tags: ansible-playbook nansible-tags.yaml --skip-tags create_user,install_git







# Another TAGS Example: To execute or skip specific tasks

# - name: first playbook
#   hosts: all
#   tasks:
#     - name: installing git
#       yum:
#        name: git
#        state: present
#       tags: a
#     - name: installing httpd
#       yum:
#         name: maven
#         state: present
#       tags: b
#     - name: create user
#       user:
#         name: test
#         state: present
#       tags: c    

#SINGLE TAG: ansible-playbook ansible-tags.yaml --tags a
#MULTI TAG: ansible-playbook nansible-tags.yaml --tags b,c
#SKIP TAG: ansible-playbook ansible-tags.yaml --skip-tags "c"
#MULTI SKIP TAGS: ansible-playbook nansible-tags.yaml --skip-tags "c,d"

